function k(b,a,c,d){b.v.Ab(b.cb,a,c,d,void 0)}function l(b,a,c,d){b.v.ga?k(b,a,c,d):b.v.qe()._OnMessageFromDOM({type:"event",component:b.cb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.cb,a,c)}function aa(b,a){for(const [c,d]of a)n(b,c,d)}function r(b){b.Kb||(b.v.je(b.Id),b.Kb=!0)}window.Va=class{constructor(b,a){this.v=b;this.cb=a;this.Kb=!1;this.Id=()=>this.wa()}Tc(){}wa(){}};function ba(b){-1!==b.Sa&&(self.clearTimeout(b.Sa),b.Sa=-1)}
window.ge=class{constructor(b){this.zc=b;this.Fe=5;this.Sa=-1;this.Mb=-Infinity;this.Jd=()=>{this.Sa=-1;this.Mb=Date.now();this.ib=!0;this.zc();this.ib=!1};this.ld=this.ib=!1}j(){ba(this);this.Jd=this.zc=null}};"use strict";function ca(b,a){n(b,"get-element",c=>{const d=b.ea.get(c.elementId);return a(d,c)})}
window.Ze=class extends self.Va{constructor(b,a){super(b,a);this.ea=new Map;this.yc=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ea.get(c);this.yc&&d.parentElement.removeChild(d);this.ea.delete(c)}],["set-visible",c=>{this.yc&&(this.ea.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.yc){var d=this.ea.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ea.get(c.elementId);throw Error("required override");}],["focus",c=>{const d=this.ea.get(c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{this.ea.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.ea.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ea.get(c.elementId).removeAttribute(c.name)}]]);ca(this,c=>c)}};"use strict";
const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let ea=0;function v(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Pe?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Te+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;
function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let w=new Audio;const ja={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;
async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const x=[];let y=0;window.RealFile=window.File;const A=[],B=new Map,C=new Map;let ma=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);
let pa=!1;
window.$a=class b{constructor(a){this.ga=a.Ve;this.sa=null;this.$="";this.ac=a.Se;this.wb={};this.La=this.vb=null;this.Ib=[];this.H=this.Qa=null;this.Hc=!1;this.od=0;this.kb=null;this.Pa=-1;this.Ke=()=>this.xe();this.Oa=[];this.D=a.Kd;this.Lb="file"===location.protocol.substr(0,4);!this.ga||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ga=!1);if("playable-ad"===this.D||"instant-games"===this.D)this.ga=!1;if("cordova"===this.D&&this.ga)if(u){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ga=!1)}else this.ga=!1;this.Pb=this.la=null;"html5"!==this.D||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.te(c));this.C("runtime","create-job-worker",()=>this.ue());"cordova"===this.D?document.addEventListener("deviceready",()=>this.cd(a)):this.cd(a)}j(){this.pc();
this.sa&&(this.sa=this.sa.onmessage=null);this.vb&&(this.vb.terminate(),this.vb=null);this.La&&(this.La.j(),this.La=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}de(){return da&&"cordova"===this.D}lc(){const a=navigator.userAgent;return da&&oa.has(this.D)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}be(){return u}Yc(){return u&&oa.has(this.D)}async cd(a){"macos-wkwebview"===this.D&&this.Ce();if("playable-ad"===this.D){this.la=self.c3_base64files;this.Pb={};await this.me();
for(let d=0,e=a.Ta.length;d<e;++d){var c=a.Ta[d].toLowerCase();this.Pb.hasOwnProperty(c)?a.Ta[d]={Pe:!0,Te:this.Pb[c]}:this.la.hasOwnProperty(c)&&(a.Ta[d]=URL.createObjectURL(this.la[c]))}}a.Re?this.$=a.Re:(c=location.origin,this.$=("null"===c?"file:///":c)+location.pathname,c=this.$.lastIndexOf("/"),-1!==c&&(this.$=this.$.substr(0,c+1)));a.Xe&&(this.wb=a.Xe);c=new MessageChannel;this.sa=c.port1;this.sa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.we(d));this.kb=new self.ee(this);await qa(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ga?await this.se(a,c.port2):await this.re(a,c.port2)}rc(a){a=this.wb.hasOwnProperty(a)?this.wb[a]:a.endsWith("/workermain.js")&&this.wb.hasOwnProperty("workermain.js")?this.wb["workermain.js"]:
"playable-ad"===this.D&&this.la.hasOwnProperty(a.toLowerCase())?this.la[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async fc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.D&&this.Lb)return a=await this.yb(d.Oe?a:this.ac+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}bd(a){var c=this.$,d=location.href,e=this.qa(),f=this.ia(),g=window.devicePixelRatio,h=b.Ya(),m=a.cf,p=window.cr_previewImageBlobs||this.la,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,z=window.af||"";a=a.Kd;var W=(new URLSearchParams(self.location.search)).has("debug"),D=this.kb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:z,exportType:a,isDebug:W,ife:!!self.bf,jobScheduler:{inputPort:D.Gc,outputPort:D.Nc,maxNumWorkers:D.He},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ac+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ac+"opus.wasm.wasm",isFileProtocol:this.Lb,isiOSCordova:this.de(),isiOSWebView:this.lc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async se(a,
c){var d=this.rc(a.We);this.vb=await this.fc(d,this.$,{type:"module",name:"Runtime",Oe:!0});this.H=document.createElement("canvas");this.H.style.display="none";d=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Sc||[],f=a.Ta;e=await Promise.all(e.map(g=>this.Ga(g)));f=await Promise.all(f.map(g=>this.Ga(g)));if("cordova"===this.D)for(let g=0,h=a.dc.length;g<h;++g){const m=a.dc[g],p=
m[0];if(p===a.Qc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ga(p)}this.vb.postMessage(Object.assign(this.bd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.dc,mainProjectScript:a.Qc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ra(this.kb)]);this.Ib=A.map(g=>new g(this));this.ad();self.c3_callFunction=(g,h)=>{var m=this.Qa;return m.v.$c(m.cb,"js-invoke-function",{name:g,params:h},
void 0,void 0)};"preview"===this.D&&(self.goToLastErrorScript=()=>this.Ab("runtime","go-to-last-error-script"))}async re(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ib=A.map(g=>new g(this));this.ad();var d=a.Ta.map(g=>"string"===typeof g?(new URL(g,this.$)).toString():g);Array.isArray(a.Sc)&&d.unshift(...a.Sc);d=await Promise.all(d.map(g=>this.Ga(g)));
await Promise.all(d.map(g=>v(g)));d=self.C3_ProjectScriptsStatus;const e=a.Qc,f=a.dc;for(let [g,h]of f)if(h||=g,g===e)try{h=await this.Ga(h),await v(h),"preview"!==this.D||d[g]||this.ed(g,"main script did not run to completion")}catch(m){this.ed(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ga(h),await v(h);"preview"===this.D&&"object"!==typeof self.Ye.$e?(this.Eb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.bd(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:na}),this.dd(),this.La=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.La,a))}ed(a,c){this.Eb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}dd(){this.Eb()}Eb(){const a=
window.Me;a&&(a.parentElement.removeChild(a),window.Me=null)}async ue(){const a=await sa(this.kb);return{outputPort:a,transferables:[a]}}qe(){if(this.ga)throw Error("not available in worker mode");return this.La}Ab(a,c,d,e,f){this.sa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}$c(a,c,d,e,f){const g=ma++,h=new Promise((m,p)=>{C.set(g,{resolve:m,reject:p})});this.sa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.ve(a);if("result"===c)this.ye(a);else if("runtime-ready"===c)this.ze();else if("alert-error"===c)this.Eb(),alert(a.message);else if("creating-runtime"===c)this.dd();else throw Error(`unknown message '${c}'`);}ve(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=B.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Db(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Db(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Db(f,!1,""+h)}):this.Db(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Db(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.sa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}ye(a){const c=a.responseId,d=a.isOk;a=a.result;const e=C.get(c);d?e.resolve(a):e.reject(a);C.delete(c)}C(a,
c,d){let e=B.get(a);e||(e=new Map,B.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static xb(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}ad(){for(const a of this.Ib)if("runtime"===a.cb){this.Qa=a;return}throw Error("cannot find runtime DOM handler");}we(a){this.Ab("debugger","message",a)}ze(){for(const a of this.Ib)a.Tc()}static Ya(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
pa)}static fd(a){pa=!!a}je(a){this.Oa.push(a);this.wc()}Be(a){a=this.Oa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Oa.splice(a,1);this.Oa.length||this.pc()}wc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Ke))}pc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}xe(){this.Pa=-1;for(const a of this.Oa)a();this.wc()}xa(a){this.Qa.xa(a)}Fa(a){this.Qa.Fa(a)}vc(){this.Qa.vc()}Cb(a){this.Qa.Cb(a)}ce(){return!!ja["audio/webm; codecs=opus"]}async De(a){a=await this.$c("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}he(a){this.Hc=!0;this.od=a}ae(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Zc(a){return!this.ae(a)}async Ga(a){return"cordova"===this.D&&(a.startsWith("file:")||this.Lb&&this.Zc(a))?(a.startsWith(this.$)&&(a=a.substr(this.$.length)),a=await this.yb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async te(a){const c=a.filename;switch(a.as){case "text":return await this.$d(c);
case "buffer":return await this.yb(c);default:throw Error("unsupported type");}}Wc(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async $d(a){a=await this.Wc(a);return await ka(a)}qc(){if(x.length&&!(8<=y)){y++;var a=x.shift();this.ne(a.filename,a.Ue,a.Ne)}}yb(a){return new Promise((c,d)=>{x.push({filename:a,Ue:e=>{y--;this.qc();c(e)},Ne:e=>{y--;this.qc();d(e)}});this.qc()})}async ne(a,
c,d){try{const e=await this.Wc(a),f=await la(e);c(f)}catch(e){d(e)}}Ce(){var a={type:"ready"};if("windows-webview2"===this.D)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.D)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async me(){const a=[];for(const [c,d]of Object.entries(this.la))a.push(this.le(c,d));await Promise.all(a)}async le(a,c){if("object"===typeof c)this.la[a]=new Blob([c.str],
{type:c.type}),this.Pb[a]=c.str;else{let d=await this.pe(c);d||=this.oe(c);this.la[a]=d}}async pe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}oe(a){a=this.Ae(a);return this.ke(a.data,a.Qe)}Ae(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");
var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Qe:a,data:d}}ke(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const E=self.$a;
function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},G={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function xa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function H(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function za(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await H(b);var d=await ya(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await H(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await H(b)}
function I(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function J(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await H(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await za(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}
function Fa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ga(b){self.setTimeout(()=>{b.nd=!0},1E3);"cordova"===b.v.D?(document.addEventListener("pause",()=>Ia(b,!0)),document.addEventListener("resume",()=>Ia(b,!1))):document.addEventListener("visibilitychange",()=>Ia(b,document.hidden));return{isSuspended:!(!document.hidden&&!K)}}
function Ja(b){b.hd||(b.hd=!0,window.addEventListener("deviceorientation",a=>{b.Y||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.Y||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Ka(b){b.gd||(b.gd=!0,window.addEventListener("devicemotion",a=>{if(!b.Y){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function La(b){await wa(b.url)}
function Ma(b,a){b.pd=a.message;-1===b.Cc&&(b.Cc=setTimeout(()=>{b.Cc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.pd)},250))}function L(b){if(!b.Y){var a=E.Ya();a&&"any"!==b.Oc&&Na(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ia()})}}function Oa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:E.Ya(),innerWidth:b.qa(),innerHeight:b.ia()})}
function Ia(b,a){a?b.v.pc():b.v.wc();k(b,"visibilitychange",{hidden:a})}function Pa(b,a,c){"Backspace"===c.key&&J(c);if(!b.Y){var d=ua.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}
function Qa(b,a,c,d){b.Y||ta(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Ra(b){window!==window.top&&window.focus();Sa(b.target)&&document.activeElement&&!Sa(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Y){if(b.sb&&"pointermove"!==a){var d=b.sb;d.ib||(ba(d),d.Mb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.pb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+b.Wb,movementY:(c.movementY||0)+b.Xb,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,
twist:c.twist||0,timeStamp:c.timeStamp},F);b.Wb=0;b.Xb=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Qa(b,d,c,va),b.pb=c.buttons)}}
function Ta(b,a,c){if(!b.Y&&!ta(c)){var d=b.pb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.pb=c.buttons;Qa(b,c.type,c,va)}}
function N(b,a,c){if(!b.Y)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},F)}}
function Wa(b,a){document.body.style.transform="";if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`))}}function Xa(b,a,c,d){const e=b.qa(),f=b.ia();b.Ra=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.Ya()}):10>d&&Ya(b,e,f,d+1)}
function Ya(b,a,c,d){-1!==b.Ra&&clearTimeout(b.Ra);b.Ra=setTimeout(()=>Xa(b,a,c,d),48)}
function Na(b){b=b.Oc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Sa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.xb(class extends self.Va{constructor(b){super(b,"runtime");this.ud=!0;this.Ra=-1;this.Oc="any";this.gd=this.hd=!1;this.Aa=null;this.Y=!1;this.pd="";this.Cc=-1;this.Ka=this.sb=null;this.Xb=this.Wb=0;this.nd=!1;this.zd=b.qa();this.Nb=b.ia();this.ub=0;b.C("canvas","update-size",d=>{var e=this.v;e.Hc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.ud&&(e.style.display="",this.ud=!1))});b.C("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","raster-svg-image",d=>Da(d));b.C("runtime","get-svg-image-size",d=>Ea(d));b.C("runtime","set-target-orientation",d=>{this.Oc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Fa(d));b.C("runtime","go-to-script",d=>
Fa(d));b.C("runtime","before-start-ticking",()=>Ga(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Aa||(this.Aa=document.createElement("div"),this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));var e=this.Aa;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Aa&&(this.Aa.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ja(this));b.C("runtime","enable-device-motion",
()=>Ka(this));b.C("runtime","add-stylesheet",d=>La(d));b.C("runtime","alert",d=>{alert(d.message)});b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Y=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.he(d.duration)});b.C("runtime",
"export-to-video-progress",d=>Ma(this,d));b.C("runtime","exported-to-video",d=>{window.Le({type:"exported-video",blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Le({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||I(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",
J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.pb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Y){var d=this.qa();var e=this.ia();if(this.v.Yc()){if(this.nd){if(this.zd===d&&e<this.Nb){this.ub=this.Nb-e;Wa(this.Nb,this.ub);d=void 0;break a}0<this.ub&&(this.ub=0,Wa(e,this.ub))}this.zd=d;this.Nb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.Ya()});this.v.lc()&&(-1!==this.Ra&&clearTimeout(this.Ra),Xa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",
()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Oa(this,d));window.addEventListener("webkitfullscreenerror",d=>Oa(this,d));window.addEventListener("mozfullscreenerror",d=>Oa(this,d));if(b.lc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):I(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(E.fd(!0),L(this)):"exited-fullscreen"===d?(E.fd(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Ma=new Set;this.Rb=new WeakSet;this.ra=!1}Tc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,G)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},G);this.pb=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||I(a))&&k(this,"keyboard-blur",null,G)});window.addEventListener("keydown",a=>Pa(this,"keydown",a));window.addEventListener("keyup",a=>Pa(this,"keyup",a));window.addEventListener("dblclick",a=>Qa(this,"dblclick",a,F));window.addEventListener("wheel",
a=>{this.Y||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Ra(a);M(this,"pointerdown",a)}),this.v.ga&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.ge(()=>{M(this,"pointermove",this.Ka);this.Ka=null}),this.sb.ld=!0,window.addEventListener("pointerrawupdate",
a=>{this.Ka&&(this.Wb+=this.Ka.movementX||0,this.Xb+=this.Ka.movementY||0);this.Ka=a;a=this.sb;if(-1===a.Sa){var c=Date.now(),d=c-a.Mb,e=a.Fe;d>=e&&a.ld?(a.Mb=c,a.ib=!0,a.zc(),a.ib=!1):a.Sa=self.setTimeout(a.Jd,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Ra(a);Ta(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Ta(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ta(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Ra(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.vc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.be()&&!this.v.Yc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Wa(this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.v.qa()}ia(){return this.v.ia()}vc(){var b=[...this.Ma];this.Ma.clear();if(!this.ra)for(const a of b)(b=a.play())&&b.catch(()=>{this.Rb.has(a)||this.Ma.add(a)})}xa(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Rb.delete(b);let a;try{a=b.play()}catch(c){this.Ma.add(b);return}a&&a.catch(()=>{this.Rb.has(b)||this.Ma.add(b)})}Fa(b){this.Ma.delete(b);this.Rb.add(b)}Cb(b){this.ra=!!b}});"use strict";
async function qa(b){if(b.Ee)throw Error("already initialised");b.Ee=!0;var a=b.$b.rc("dispatchworker.js");b.Bc=await b.$b.fc(a,b.bb,{name:"DispatchWorker"});a=new MessageChannel;b.Gc=a.port1;b.Bc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Nc=await sa(b)}function ra(b){return[b.Gc,b.Nc]}
async function sa(b){const a=b.wd.length;var c=b.$b.rc("jobworker.js");c=await b.$b.fc(c,b.bb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Bc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.wd.push(c);return e.port1}
self.ee=class{constructor(b){this.$b=b;this.bb=b.$;this.bb="preview"===b.D?this.bb+"workers/":this.bb+b.ac;this.He=Math.min(navigator.hardwareConcurrency||2,16);this.Bc=null;this.wd=[];this.Nc=this.Gc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.$a({Ve:!0,We:"workermain.js",Ta:["scripts/c3runtime.js"],dc:[],Qc:"",Se:"scripts/",Sc:["box2d.wasm.js"],Kd:"html5"}));"use strict";let Za=!1;
async function ab(b){var a=bb(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function O(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Za||(console.warn("[Construct] Failed to access gamepads: ",b),Za=!0),[]}}
function bb(b){for(const a of O())if(a.index===b)return a;return null}
self.$a.xb(class extends self.Va{constructor(b){super(b,"gamepad");this.vd=!!navigator.getGamepads;this.Jc=!1;n(this,"is-supported",()=>this.vd);n(this,"ready",()=>{this.Jc=!0;for(const a of O())k(this,"gamepad-connected",{index:a.index,id:a.id});this.vd&&r(this)});n(this,"vibrate",a=>ab(a));n(this,"reset-vibrate",a=>{(a=bb(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Jc&&(a=a.gamepad,k(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Jc&&k(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of O()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}wa(){var b=O();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),k(this,"input-update",b))}});"use strict";
async function cb(b,a){a=a.type;let c=!0;0===a?c=await db():1===a&&(c=await eb());k(b,"permission-result",{type:a,result:c})}async function db(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function eb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.$a.xb(class extends self.Va{constructor(b){super(b,"touch");n(this,"request-permission",a=>cb(this,a))}});"use strict";const fb=180/Math.PI;
async function gb(b,a){a.isiOSCordova&&(b.Ub=!0);b.Pc=a.timeScaleMode;b.Bd=["equalpower","HRTF","soundfield"][a.panningModel];b.md=["linear","inverse","exponential"][a.distanceModel];b.Cd=a.refDistance;b.Ad=a.maxDistance;b.Ed=a.rolloffFactor;if(b.v.Hc)b.Ub=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.od)});else{var c={latencyHint:a.latencyHint};b.Hd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");hb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&hb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ia=b.g.createGain();b.Ia.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state}}
async function ib(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.xd=g;jb(b,g);try{b.ka=await kb(b,c,d,e,g,f);if(q){Q(b.ka,!0);var z=b.ka,W=q.innerAngle,D=q.outerAngle,wb=q.outerGain;if(z.jb){lb(z,q.x,q.y,q.angle);var Ha=self.Ua.ie;z.F.coneInnerAngle=Ha(W);z.F.coneOuterAngle=
Ha(D);z.F.coneOuterGain=wb}q.hasOwnProperty("uid")&&(b.ka.ja=q.uid)}else Q(b.ka,!1);b.ka.Play(h,m,p,t)}catch(xb){console.error("[Construct] Audio: error starting playback: ",xb);return}finally{c=b.rb.get(g);if(!c)throw Error("expected pending tag");c.Rc--;0===c.Rc&&(c.resolve(),b.rb.delete(g))}r(b)}
async function mb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await nb(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ja){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Da=f;c.gb=g;c.Gd=h}}S(b)}async function ob(b,a){const c=a.tag;a=a.rate;await nb(b,c);for(const d of R(b,c))b=d,b.fa!==a&&(b.fa=a,b.ya())}
async function pb(b,a){const c=a.tag;a=a.pos;await nb(b,c);for(const d of R(b,c))d.mc(a)}async function qb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await kb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function rb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ca.indexOf(a),-1!==a&&b.ca.splice(a,1)}
async function sb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Qd(b,...e);else if("delay"===c)e=new self.Od(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Nd(b,c.ba,...e);var f=a.bufferType;c.jd=a.bufferOriginalUrl;c.kd=f}else if("flanger"===c)e=new self.Rd(b,...e);else if("phaser"===c)e=new self.Td(b,...e);else if("gain"===c)e=
new self.Sd(b,...e);else if("tremolo"===c)e=new self.Vd(b,...e);else if("ringmod"===c)e=new self.Ud(b,...e);else if("distortion"===c)e=new self.Pd(b,...e);else if("compressor"===c)e=new self.Md(b,...e);else if("analyser"===c)e=new self.Ld(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.da.get(d);e||(e=[],b.da.set(d,e));a.td=e.length;a.aa=d;e.push(a);tb(b,d);ub(b)}
async function vb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.va()&&1===c||(d.va()||2!==c)&&d.pa();for(const e of b.da.values())for(const f of e)f.j();b.da.clear();b.bc=a.timeScale;b.Dc=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.ra=a.isSilent;b.v.Cb(b.ra);b.Qb=a.masterVolume;b.Ia.gain.value=b.Qb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>sb(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>yb(b,e,c)));S(b)}
async function zb(b,a){try{const c=b.g.suspend(a.time);b.sd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Ab("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ab(d)),b.sd=!0);await c}catch(c){Ab(c)}}
function hb(b){b.Jb||(b.Fc=!1,window.addEventListener("pointerup",b.ta,!0),window.addEventListener("touchend",b.ta,!0),window.addEventListener("click",b.ta,!0),window.addEventListener("keydown",b.ta,!0),b.Jb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ca)if(g.Xa()===c)return await Bb(g),g;if(f)return null;if(e&&(b.Ub||b.rd)){f=0;for(let h=0,m=b.ca.length;h<m;++h)g=b.ca[h],b.ca[f]=g,g.va()?g.j():++f;b.ca.length=f}f="audio/webm; codecs=opus"===d&&!b.Hd;e&&f&&(b.rd=!0);a=!e||b.Ub||f?new self.Yd(b,a,c,d,e,f):new self.Wd(b,a,c,d,e);b.ca.push(a);await Bb(a);return a}function Cb(b,a){return(a=b.da.get(a.toLowerCase()))?a[0].R():b.ua()}
function tb(b,a){let c=b.ua();var d=b.da.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ua()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Ba&&b.Lc===a&&(b.Ba.disconnect(),b.Ba.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.aa,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.ka&&!b.ka.S()&&(yield b.ka)}
function Db(b,a,c){return c?b.v.De(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Eb(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function kb(b,a,c,d,e,f){for(const g of b.L)if(g.Xa()===c&&(g.ec()||f))return g.aa=e,g;a=await P(b,a,c,d,f);e="html5"===a.xc?new self.Xd(a.s,a,e):new self.Zd(a.s,a,e);b.L.push(e);return e}
function jb(b,a){let c=b.rb.get(a);if(!c){let d=null;c={Rc:0,promise:new Promise(e=>d=e),resolve:d};b.rb.set(a,c)}c.Rc++}function nb(b,a){a||(a=b.xd);return(b=b.rb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ha.size)r(b);else for(const a of b.L)if(!a.G&&!a.S()){r(b);break}}function Fb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function ub(b){b.Ic||(b.Ic=!0,Promise.resolve().then(()=>Gb(b)))}
function Gb(b){const a={};for(const [c,d]of b.da)a[c]=d.map(e=>e.Wa());k(b,"fxstate",{fxstate:a});b.Ic=!1}
async function yb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await kb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;a.pan?(Q(b,!0),d=b.F,e=d.pos,b.na[0]=e[0],b.na[1]=e[1],b.na[2]=e[2],e=d.orient,b.ma[0]=e[0],b.ma[1]=e[1],b.ma[2]=e[2],d.setPosition(...b.na),d.setOrientation(...b.ma),d.coneInnerAngle=d.cia,d.coneOuterAngle=
d.coa,d.coneOuterGain=d.cog,b.ja=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.Za();c.tc(a)}}}function Ab(b){console.error("[Audio] Offline rendering error: ",b)}
self.Ua=class extends self.Va{constructor(b){super(b,"audio");this.Ia=this.g=null;this.Jb=this.Fc=!1;this.ta=()=>{if(!this.Fc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Jb&&(this.Fc=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",
this.ta,!0),this.Jb=!1)}};this.ca=[];this.L=[];this.ka=null;this.xd="";this.yd=-1;this.rb=new Map;this.Qb=1;this.ra=!1;this.Pc=0;this.bc=1;this.Dc=0;this.Bd="HRTF";this.md="inverse";this.Cd=600;this.Ad=1E4;this.Ed=1;this.rd=this.Ub=!1;this.Hd=this.v.ce();this.da=new Map;this.Ha=new Set;this.sd=this.Ic=!1;this.Lc="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ba&&this.Ba.disconnect();this.Lc=c.toLowerCase();this.Ba=this.g.createMediaStreamSource(a);this.Ba.connect(Cb(this,this.Lc))};
this.Hb=null;self.C3Audio_GetOutputStream=()=>{this.Hb||(this.Hb=this.g.createMediaStreamDestination(),this.Ia.connect(this.Hb));return this.Hb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>gb(this,a)],["play",a=>ib(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.pa()}],["stop-all",()=>{for(const a of this.L)a.pa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.Za():d.Bb();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of R(this,
c))T(d,a)}],["fade-volume",a=>mb(this,a)],["set-master-volume",a=>{this.Qb=a.vol;this.Ia.gain.value=this.Qb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Hb(d,a)}],["set-silent",a=>{this.ra=a.isSilent;this.v.Cb(this.ra);for(const c of this.L)c.Fb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.nc(a)}],["set-playback-rate",a=>ob(this,a)],["seek",a=>pb(this,a)],["preload",a=>qb(this,a)],["unload",a=>rb(this,a)],["unload-all",()=>{for(const a of this.ca)a.j();
this.ca.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.oc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>sb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.da.get(a.tag);!a||0>c||c>=a.length||(a[c].Z(d,e,f,g),ub(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.da.get(a);if(c&&c.length){for(const d of c)d.j();this.da.delete(a);tb(this,a)}}],["tick",a=>{this.bc=a.timeScale;
this.Dc=a.gameTime;this.yd=a.tickCount;if(0!==this.Pc)for(var c of this.L)c.ya();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ja===a&&lb(e,d.x,d.y,d.angle)}}],["load-state",a=>vb(this,a)],["offline-render-audio",a=>zb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}X(){return this.g}ua(){return this.Ia}zb(){return this.ra}xa(b){this.v.xa(b)}Fa(b){this.v.Fa(b)}wa(){for(var b of this.Ha)b.wa();b=this.g.currentTime;
for(var a of this.L)a.wa(b);a=this.L.filter(c=>!c.G&&!c.S()).map(c=>c.Wa());k(this,"state",{tickCount:this.yd,audioInstances:a,analysers:[...this.Ha].map(c=>({tag:c.aa,index:c.td,peak:c.Na,rms:c.Dd,binCount:c.m.frequencyBinCount,freqBins:c.qd}))});0===a.length&&0===this.Ha.size&&this.Kb&&(this.v.Be(this.Id),this.Kb=!1)}static ie(b){return b*fb}static Xc(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static fe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.$a.xb(self.Ua);
"use strict";function Bb(b){b.Ob||(b.Ob=b.sc());return b.Ob}self.Uc=class{constructor(b,a,c,d,e){this.s=b;this.Je=a;this.Ca=c;this.T=d;this.Ge=e;this.xc="";this.Ob=null}j(){this.Ob=this.s=null}sc(){}X(){return this.s.X()}ic(){return this.Je}Xa(){return this.Ca}hc(){return this.T}va(){return this.Ge}ha(){}};"use strict";
self.Wd=class extends self.Uc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.xc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.lb=this.mb=null;this.K.addEventListener("canplaythrough",()=>!0);this.qb=this.X().createGain();this.ob=null;this.K.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.K&&(this.ob=this.X().createMediaElementSource(this.K),this.ob.connect(this.qb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ca}' error: `,f);this.lb&&(this.lb(f),this.lb=this.mb=null)})}j(){Eb(this.s,this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}sc(){return new Promise((b,a)=>{this.mb=b;this.lb=a;this.K.src=this.Ca})}P(){return this.K}ha(){return this.K.duration}};"use strict";
async function Ib(b){if(b.za)return b.za;var a=b.s.v;if("cordova"===a.D&&a.Zc(b.Ca)&&a.Lb)b.za=await a.yb(b.Ca);else{a=await fetch(b.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.za=await a.arrayBuffer()}}async function Jb(b){if(b.ba)return b.ba;b.ba=await Db(b.s,b.za,b.Ie);b.za=null}
self.Yd=class extends self.Uc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.xc="webaudio";this.ba=this.za=null;this.Ie=!!f}j(){Eb(this.s,this);this.ba=this.za=null;super.j()}async sc(){try{await Ib(this),await Jb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ca}': `,b)}}ha(){return this.ba?this.ba.duration:0}};"use strict";let Kb=0;
function Q(b,a){a=!!a;b.jb!==a&&(b.jb=a,b.jb?(b.F||(b.F=b.X().createPanner(),b.F.panningModel=b.s.Bd,b.F.distanceModel=b.s.md,b.F.refDistance=b.s.Cd,b.F.maxDistance=b.s.Ad,b.F.rolloffFactor=b.s.Ed),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.ua())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.ua())))}function T(b,a){b.Da=a;b.N.gain.cancelScheduledValues(0);b.gb=-1;b.N.gain.value=b.jc()}function Hb(b,a){a=!!a;b.Ja!==a&&(b.Ja=a,b.Fb())}
function lb(b,a,c,d){b.jb&&(b.na[0]=a,b.na[1]=c,b.na[2]=0,b.ma[0]=Math.cos(d),b.ma[1]=Math.sin(d),b.ma[2]=0,b.F.setPosition(...b.na),b.F.setOrientation(...b.ma))}function U(b){return b.Kc?b.s.Dc:performance.now()/1E3}
self.Vc=class{constructor(b,a,c){this.s=b;this.M=a;this.aa=c;this.Gb=Kb++;this.N=this.X().createGain();this.N.connect(this.ua());this.F=null;this.jb=!1;this.na=[0,0,0];this.ma=[0,0,0];this.G=!0;this.W=this.oa=this.I=!1;this.Da=1;this.Ja=!1;this.fa=1;b=this.s.Pc;this.Kc=1===b&&!this.va()||2===b;this.gb=this.ja=-1;this.Gd=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}X(){return this.s.X()}ua(){return Cb(this.s,this.aa)}ic(){return this.M.ic()}Xa(){return this.M.Xa()}hc(){return this.M.hc()}va(){return this.M.va()}S(){}ec(){}IsPlaying(){return!this.G&&
!this.I&&!this.S()}Ea(){}ha(){return this.M.ha()}Play(){}pa(){}Za(){}Bb(){}wa(b){-1!==this.gb&&b>=this.gb&&(this.gb=-1,this.Gd&&this.pa(),Fb(this.s,"fade-ended",this.aa,this.Gb))}jc(){const b=this.Da;return isFinite(b)?b:0}zb(){return this.s.zb()}Fb(){}nc(){}ya(){}mc(){}oc(){}kc(){}Wa(){var b=this.Gb,a=this.aa,c=this.ha(),d=this.Da,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.na,orient:this.ma,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ja}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ea(),playbackRate:this.fa,uid:this.ja,bufferOriginalUrl:this.ic(),bufferUrl:"",bufferType:this.hc(),isMusic:this.va(),isLooping:this.W,isMuted:this.Ja,resumePosition:this.kc(),pan:f}}tc(b){var a=b.playbackRate;this.fa!==a&&(this.fa=a,this.ya());Hb(this,b.isMuted)}};"use strict";
self.Xd=class extends self.Vc{constructor(b,a,c){super(b,a,c);this.M.qb.connect(this.N);this.M.onended=()=>this.uc()}j(){this.pa();this.M.qb.disconnect();super.j()}P(){return this.M.P()}uc(){this.G=!0;this.ja=-1;Fb(this.s,"ended",this.aa,this.Gb)}S(){return this.P().ended}ec(){return this.G?!0:this.S()}Ea(){let b=this.P().currentTime;this.W||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.Xa()}' to position '${c}': `,e)}this.s.xa(d);this.I=this.G=!1;this.W=b;this.fa=1}pa(){const b=this.P();b.paused||b.pause();this.s.Fa(b);this.G=!0;this.I=!1;this.ja=-1}Za(){if(!(this.I||this.G||this.S())){var b=this.P();b.paused||b.pause();this.s.Fa(b);this.I=!0}}Bb(){!this.I||this.G||this.S()||(this.s.xa(this.P()),this.I=!1)}Fb(){this.P().muted=this.Ja||this.zb()}nc(b){b=!!b;this.W!==b&&(this.W=
b,this.P().loop=b)}ya(){let b=this.fa;this.Kc&&(b*=this.s.bc);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}mc(b){if(!this.G&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}kc(){return this.Ea()}oc(b){b?this.IsPlaying()?(this.P().pause(),this.oa=!0):this.oa=!1:this.oa&&(this.s.xa(this.P()),this.oa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.ab=null}
self.Zd=class extends self.Vc{constructor(b,a,c){super(b,a,c);this.o=null;this.Sb=d=>this.uc(d);this.Ec=!0;this.ab=null;this.O=this.Tb=this.Vb=0;this.Mc=1}j(){this.pa();V(this);this.Sb=null;super.j()}uc(b){this.I||this.oa||b.target!==this.ab||(this.G=this.Ec=!0,this.ja=-1,V(this),Fb(this.s,"ended",this.aa,this.Gb))}S(){return!this.G&&this.o&&this.o.loop||this.I?!1:this.Ec}ec(){return!this.o||this.G?!0:this.S()}Ea(){let b;b=this.I?this.O:this.Tb+(U(this)-this.Vb)*this.fa;this.W||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Mc=1;T(this,a);V(this);this.o=this.X().createBufferSource();this.o.buffer=this.M.ba;this.o.connect(this.N);this.ab=this.o;this.o.onended=this.Sb;this.o.loop=b;this.o.start(d,c);this.I=this.G=this.Ec=!1;this.W=b;this.fa=1;this.Vb=U(this);this.Tb=c}pa(){if(this.o)try{this.o.stop(0)}catch(b){}this.G=!0;this.I=!1;this.ja=-1}Za(){this.I||this.G||this.S()||(this.O=this.Ea(),this.W&&(this.O%=this.ha()),this.I=!0,this.o.stop(0))}Bb(){!this.I||this.G||this.S()||(V(this),this.o=
this.X().createBufferSource(),this.o.buffer=this.M.ba,this.o.connect(this.N),this.ab=this.o,this.o.onended=this.Sb,this.o.loop=this.W,T(this,this.Da),this.ya(),this.o.start(0,this.O),this.Vb=U(this),this.Tb=this.O,this.I=!1)}jc(){return super.jc()*this.Mc}Fb(){this.Mc=this.Ja||this.zb()?0:1;T(this,this.Da)}nc(b){b=!!b;this.W!==b&&(this.W=b,this.o&&(this.o.loop=b))}ya(){let b=this.fa;this.Kc&&(b*=this.s.bc);this.o&&(this.o.playbackRate.value=b)}mc(b){this.G||this.S()||(this.I?this.O=b:(this.Za(),this.O=
b,this.Bb()))}kc(){return this.O}oc(b){b?this.IsPlaying()?(this.oa=!0,this.O=this.Ea(),this.W&&(this.O%=this.ha()),this.o.stop(0)):this.oa=!1:this.oa&&(V(this),this.o=this.X().createBufferSource(),this.o.buffer=this.M.ba,this.o.connect(this.N),this.ab=this.o,this.o.onended=this.Sb,this.o.loop=this.W,T(this,this.Da),this.ya(),this.o.start(0,this.O),this.Vb=U(this),this.Tb=this.O,this.oa=!1)}tc(b){super.tc(b);this.O=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.X();this.td=-1;this.T=this.aa="";this.l=null}j(){this.g=null}R(){}U(){}Wa(){return{type:this.T,tag:this.aa,params:this.l}}}
self.Qd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.B=this.g.createBiquadFilter();this.B.type=a;this.B.frequency.value=c;this.B.detune.value=d;this.B.Q.value=e;this.B.gain.vlaue=f;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i)}j(){this.u.disconnect();this.B.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;Y(this,this.B.frequency,a,c,d);break;case 2:this.l[2]=a;Y(this,this.B.detune,a,c,d);break;case 3:this.l[3]=a;Y(this,this.B.Q,a,c,d);break;case 4:this.l[4]=a,Y(this,this.B.gain,a,c,d)}}};
self.Od=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.nb=X(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.fb=X(this);this.fb.gain.value=c;this.u.connect(this.nb);this.u.connect(this.h);this.nb.connect(this.i);this.nb.connect(this.V);this.V.connect(this.fb);this.fb.connect(this.nb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.nb.disconnect();
this.V.disconnect();this.fb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){const e=self.Ua.Xc;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);Y(this,this.fb.gain,e(a),c,d);break;case 5:this.l[0]=a,Y(this,this.V.delayTime,a,c,d)}}};
self.Nd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.kd=this.jd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.eb=this.g.createConvolver();this.eb.normalize=c;this.eb.buffer=a;this.u.connect(this.eb);this.u.connect(this.h);this.eb.connect(this.i)}j(){this.u.disconnect();this.eb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}Wa(){const b=super.Wa();b.bufferOriginalUrl=this.jd;b.bufferUrl="";b.bufferType=this.kd;return b}};
self.Rd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.hb=X(this);this.hb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.J=X(this);this.J.gain.value=c;this.u.connect(this.V);this.u.connect(this.h);this.V.connect(this.i);this.V.connect(this.hb);this.hb.connect(this.V);this.A.connect(this.J);
this.J.connect(this.V.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.V.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.hb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;Y(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.l[3]=a/100,Y(this,this.hb.gain,a/100,c,d)}}};
self.Td=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.B=this.g.createBiquadFilter();this.B.type="allpass";this.B.frequency.value=a;this.B.detune.value=c;this.B.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.J=X(this);this.J.gain.value=e;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i);this.A.connect(this.J);this.J.connect(this.B.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.B.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;Y(this,this.B.frequency,a,c,d);break;case 2:this.l[1]=a;Y(this,this.B.detune,a,c,d);
break;case 3:this.l[2]=a;Y(this,this.B.Q,a,c,d);break;case 6:this.l[3]=a;Y(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.Sd=class extends Z{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=X(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(b,a,c,d){const e=self.Ua.Xc;switch(b){case 4:this.l[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Vd=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.J=X(this);this.J.gain.value=c/2;this.A.connect(this.J);this.J.connect(this.m.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Ud=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.tb=X(this);this.tb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.tb.gain);this.A.start(0);this.u.connect(this.tb);this.u.connect(this.h);this.tb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.tb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Pd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.u=X(this);this.Zb=X(this);this.Yb=X(this);b=d;.01>b&&(b=.01);this.Zb.gain.value=b;this.Yb.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.cc=this.g.createWaveShaper();this.Ac=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ac[32768+e]=f,this.Ac[32768-
e-1]=-f;this.cc.curve=this.Ac;this.u.connect(this.Zb);this.u.connect(this.h);this.Zb.connect(this.cc);this.cc.connect(this.Yb);this.Yb.connect(this.i)}j(){this.u.disconnect();this.Zb.disconnect();this.cc.disconnect();this.Yb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Md=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(){}};
self.Ld=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.qd=new Float32Array(this.m.frequencyBinCount);this.Fd=new Uint8Array(a);this.Dd=this.Na=0;b=this.s;b.Ha.add(this);S(b)}j(){this.s.Ha.delete(this);this.m.disconnect();super.j()}wa(){this.m.getFloatFrequencyData(this.qd);this.m.getByteTimeDomainData(this.Fd);const b=this.m.fftSize;let a=this.Na=0;for(var c=0;c<b;++c){let d=(this.Fd[c]-
128)/128;0>d&&(d=-d);this.Na<d&&(this.Na=d);a+=d*d}c=self.Ua.fe;this.Na=c(this.Na);this.Dd=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(){}};
